name: Build and Dogfooding CLI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz
    - name: Build Core
      run: ./gradlew :jig-core:build
    - name: upload test report
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: failure-report
        path: jig-core/build/reports/tests/test
    - name: Build CLI
      run: ./gradlew :jig-cli:build
    - name: Run CLI
      run: java -jar jig-cli/build/libs/jig-cli.jar
    - name: Upload JIG-DOCUMENT
      uses: actions/upload-artifact@master
      with:
        name: jig-doc
        path: build/jig

