name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew :jig-core:build
    - name: upload test report
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: test-report
        path: jig-core/build/test-results

